Update script

diff --git a/usr/bin/pt-hostname b/usr/bin/pt-hostname
--- a/usr/bin/pt-hostname
+++ b/usr/bin/pt-hostname
@@ -34,11 +34,59 @@ set_hostname() {
 
 
 main() {
+	if [[ "${command}" == "set" ]]; then
+		do_set
+	elif [[ "${command}" == "publish" ]]; then
+		do_publish
+    fi
+}
+
+
+do_set() {
     new_hostname=$(produce_hostname)
     if [ "${new_hostname}" != "$(hostname)" ]; then
         set_hostname "${new_hostname}"
     fi
 }
+
+
+do_publish() {
+    until /usr/sbin/avahi-daemon -c &> /dev/null
+    do
+        echo "Waiting for avahi-daemon daemon ..."
+        sleep 1
+    done
+
+    USB_IFACE_IP=$(ip a l ptusb0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
+    /usr/bin/avahi-publish -a -R pi-top.local "${USB_IFACE_IP}"
+}
+
+
+usage_and_exit() {
+	echo "Application that sets up the pi-top hostname."
+	echo ""
+	echo -e "Usage:\\n\\t${0} {set,publish}"
+	echo "where:"
+	echo -e "\\tset\\t: set the machine hostname based on the Raspberry Pi serial number."
+	echo -e "\\tpublish\\t: publish pi-top.local hostname using avahi."
+	exit 1
+}
+
+
+if [[ "$EUID" -ne 0 ]]; then
+	echo "Please run as root"
+	exit 1
+fi
+
+
+command=${1:-}
+valid_commands=("set" "publish")
+if [[ -z "${command}" ]] || [[ ! "${valid_commands[*]}" =~ ${command} ]]; then
+	# shellcheck disable=SC2145
+	echo "Invalid argument: accepted values are: ${valid_commands[@]}."
+	echo ""
+	usage_and_exit
+fi
 
 
 main
