pt-os-init sets wifi country

diff --git a/src/pt-os-init b/src/pt-os-init
--- a/src/pt-os-init
+++ b/src/pt-os-init
@@ -88,10 +88,6 @@ do_expand() {
       i2cset -y 1 0x11 0x14 0
   fi
 
-  umount /boot
-  mount / -o remount,ro
-  sync
-  reboot -f
 }
 
 
@@ -101,8 +97,36 @@ do_prepare() {
 }
 
 
+do_set_wifi_country() {
+  mount /boot -o remount,rw
+  mount / -o remount,ro
+
+  if [ ! -f /boot/wpa_supplicant.conf ]; then
+    if [ -f /etc/wpa_supplicant/wpa_supplicant.conf ]; then
+        cp /etc/wpa_supplicant/wpa_supplicant.conf /boot/wpa_supplicant.conf
+    else
+        echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
+update_config=1
+COUNTRY=00" > /boot/wpa_supplicant.conf
+    fi
+  fi
+
+  if ! grep -q "COUNTRY=" /boot/wpa_supplicant.conf; then
+      echo "COUNTRY=00" >> /boot/wpa_supplicant.conf
+  fi
+}
+
+
+
 if [ "$#" -eq 0 ]; then
   do_expand
+  do_set_wifi_country
+
+  # Cleanup and reboot
+  umount /boot
+  mount / -o remount,ro
+  sync
+  reboot -f
 elif [ "$1" = "prepare" ]; then
   do_prepare
 fi
